import dotenv from "dotenv";
dotenv.config();

export const CONFIG = {
  DISCORD_TOKEN: process.env.DISCORD_TOKEN || "",
  CLIENT_ID: process.env.CLIENT_ID || "",
  NEWS_CHANNEL_ID: process.env.NEWS_CHANNEL_ID || "",
  NEWS_INTERVAL_MS: 300_000,
  XAUUSD_CHANNEL_ID: process.env.XAUUSD_CHANNEL_ID || "",
  MARKET_TIMES_CHANNEL_ID: process.env.MARKET_TIMES_CHANNEL_ID || "",
  LIVE_PRICES_CHANNEL_ID: process.env.LIVE_PRICES_CHANNEL_ID || "",

  STARTING_BALANCE: 10000,
  DAILY_REWARD_AMOUNT: 500,
  DAILY_REWARD_COOLDOWN_MS: 24 * 60 * 60 * 1000,
  TRANSACTION_FEE_PERCENT: 0.001,
  MAX_PORTFOLIO_NAME_LENGTH: 50,

  ADMIN_ROLES: ["Trading Admin", "Server Admin"],

  BANNED_SYMBOLS: ["PENNY1", "SCAMCOIN"],

  CACHE_TTL_MS: 30_000,

  DATA_DIR: "./data",
  ACCOUNTS_FILE: "./data/accounts.json",
  PORTFOLIOS_FILE: "./data/portfolios.json",
  TRANSACTIONS_FILE: "./data/transactions.json",
  ALERTS_FILE: "./data/alerts.json",
  WATCHLISTS_FILE: "./data/watchlists.json",
  CONFIG_FILE: "./data/server_config.json",

  EMBED_COLOR: 0x00ff88,
  ERROR_COLOR: 0xff3333,
  WARNING_COLOR: 0xffaa00,
  INFO_COLOR: 0x3399ff,

  CRYPTO_IDS: new Map<string, string>([
    ["BTC", "bitcoin"],
    ["ETH", "ethereum"],
    ["SOL", "solana"],
    ["XRP", "ripple"],
    ["DOGE", "dogecoin"],
    ["ADA", "cardano"],
    ["AVAX", "avalanche-2"],
    ["DOT", "polkadot"],
    ["MATIC", "matic-network"],
    ["SHIB", "shiba-inu"],
    ["LTC", "litecoin"],
    ["LINK", "chainlink"],
    ["UNI", "uniswap"],
    ["ATOM", "cosmos"],
    ["XLM", "stellar"],
    ["ALGO", "algorand"],
    ["VET", "vechain"],
    ["FIL", "filecoin"],
    ["ICP", "internet-computer"],
    ["NEAR", "near"],
    ["FTM", "fantom"],
    ["APE", "apecoin"],
    ["OP", "optimism"],
    ["ARB", "arbitrum"],
    ["SUI", "sui"],
  ]),

  FOREX_PAIRS: new Map<string, string>([
    ["EURUSD", "EUR/USD"],
    ["GBPUSD", "GBP/USD"],
    ["USDJPY", "USD/JPY"],
    ["USDCHF", "USD/CHF"],
    ["AUDUSD", "AUD/USD"],
    ["USDCAD", "USD/CAD"],
    ["NZDUSD", "NZD/USD"],
    ["EURGBP", "EUR/GBP"],
    ["EURJPY", "EUR/JPY"],
    ["GBPJPY", "GBP/JPY"],
  ]),

  COMMODITIES: [
    { symbol: "GC=F", name: "Gold Futures" },
    { symbol: "SI=F", name: "Silver Futures" },
    { symbol: "CL=F", name: "Crude Oil WTI" },
    { symbol: "BZ=F", name: "Brent Crude Oil" },
    { symbol: "NG=F", name: "Natural Gas" },
    { symbol: "HG=F", name: "Copper Futures" },
    { symbol: "PL=F", name: "Platinum Futures" },
    { symbol: "ZC=F", name: "Corn Futures" },
    { symbol: "ZS=F", name: "Soybean Futures" },
    { symbol: "ZW=F", name: "Wheat Futures" },
    { symbol: "KC=F", name: "Coffee Futures" },
    { symbol: "CT=F", name: "Cotton Futures" },
    { symbol: "SB=F", name: "Sugar Futures" },
  ],
};
